import createClient from "openapi-fetch";
import { paths } from "./openapi/schema.js"; // generated by openapi-typescript

export * from './types.js';

// export interface Options {
//     apiKey?: string,
// }

export default type TelzioClient = ReturnType<typeof createClient<paths>>;
